export const apeCodeList = [
    { value: '0111Z', text: '0111Z - Culture de céréales (à l\'exception du riz), de légumineuses et de graines oléagineuses' },
    { value: '0112Z', text: '0112Z - Culture du riz' },
    { value: '0113Z', text: '0113Z - Culture de légumes, de melons, de racines et de tubercules' },
    { value: '0114Z', text: '0114Z - Culture de la canne à sucre' },
    { value: '0115Z', text: '0115Z - Culture du tabac' },
    { value: '0116Z', text: '0116Z - Culture de plantes à fibres' },
    { value: '0119Z', text: '0119Z - Autres cultures non permanentes' },
    { value: '0121Z', text: '0121Z - Culture de la vigne' },
    { value: '0122Z', text: '0122Z - Culture de fruits tropicaux et subtropicaux' },
    { value: '0123Z', text: '0123Z - Culture d\'agrumes' },
    { value: '0124Z', text: '0124Z - Culture de fruits à pépins et à noyau' },
    { value: '0125Z', text: '0125Z - Culture d\'autres fruits d\'arbres ou d\'arbustes et de fruits à coque' },
    { value: '0126Z', text: '0126Z - Culture de fruits oléagineux' },
    { value: '0127Z', text: '0127Z - Culture de plantes à boissons' },
    { value: '0128Z', text: '0128Z - Culture de plantes à épices, aromatiques, médicinales et pharmaceutiques' },
    { value: '0129Z', text: '0129Z - Autres cultures permanentes' },
    { value: '0130Z', text: '0130Z - Reproduction de plantes' },
    { value: '0141Z', text: '0141Z - Élevage de vaches laitières' },
    { value: '0142Z', text: '0142Z - Élevage d\'autres bovins et de buffles' },
    { value: '0143Z', text: '0143Z - Élevage de chevaux et d\'autres équidés' },
    { value: '0144Z', text: '0144Z - Élevage de chameaux et d\'autres camélidés' },
    { value: '0145Z', text: '0145Z - Élevage d\'ovins et de caprins' },
    { value: '0146Z', text: '0146Z - Élevage de porcins' },
    { value: '0147Z', text: '0147Z - Élevage de volailles' },
    { value: '0149Z', text: '0149Z - Élevage d\'autres animaux' },
    { value: '0150Z', text: '0150Z - Culture et élevage associés' },
    { value: '0161Z', text: '0161Z - Activités de soutien aux cultures' },
    { value: '0162Z', text: '0162Z - Activités de soutien à la production animale' },
    { value: '0163Z', text: '0163Z - Traitement primaire des récoltes' },
    { value: '0164Z', text: '0164Z - Traitement des semences' },
    { value: '0170Z', text: '0170Z - Chasse, piégeage et services annexes' },
    { value: '0210Z', text: '0210Z - Sylviculture et autres activités forestières' },
    { value: '0220Z', text: '0220Z - Exploitation forestière' },
    { value: '0230Z', text: '0230Z - Récolte de produits forestiers non ligneux poussant à l\'état sauvage' },
    { value: '0240Z', text: '0240Z - Services de soutien à l\'exploitation forestière' },
    { value: '0311Z', text: '0311Z - Pêche en mer' },
    { value: '0312Z', text: '0312Z - Pêche en eau douce' },
    { value: '0321Z', text: '0321Z - Aquaculture en mer' },
    { value: '0322Z', text: '0322Z - Aquaculture en eau douce' },
    { value: '0510Z', text: '0510Z - Extraction de houille' },
    { value: '0520Z', text: '0520Z - Extraction de lignite' },
    { value: '0610Z', text: '0610Z - Extraction de pétrole brut' },
    { value: '0620Z', text: '0620Z - Extraction de gaz naturel' },
    { value: '0710Z', text: '0710Z - Extraction de minerais de fer' },
    { value: '0721Z', text: '0721Z - Extraction de minerais d\'uranium et de thorium' },
    { value: '0729Z', text: '0729Z - Extraction d\'autres minerais de métaux non ferreux' },
    { value: '0811Z', text: '0811Z - Extraction de pierres ornementales et de construction, de calcaire industriel, de gypse, de craie et d\'ardoise' },
    { value: '0812Z', text: '0812Z - Exploitation de gravières et sablières, extraction d\'argiles et de kaolin' },
    { value: '0891Z', text: '0891Z - Extraction des minéraux chimiques et d\'engrais minéraux' },
    { value: '0892Z', text: '0892Z - Extraction de tourbe' },
    { value: '0893Z', text: '0893Z - Production de sel' },
    { value: '0899Z', text: '0899Z - Autres activités extractives nca' },
    { value: '0910Z', text: '0910Z - Activités de soutien à l\'extraction d\'hydrocarbures' },
    { value: '0990Z', text: '0990Z - Activités de soutien aux autres industries extractives' },
    { value: '1011Z', text: '1011Z - Transformation et conservation de la viande de boucherie' },
    { value: '1012Z', text: '1012Z - Transformation et conservation de la viande de volaille' },
    { value: '1013A', text: '1013A - Préparation industrielle de produits à base de viande' },
    { value: '1013B', text: '1013B - Charcuterie' },
    { value: '1020Z', text: '1020Z - Transformation et conservation de poisson, de crustacés et de mollusques' },
    { value: '1031Z', text: '1031Z - Transformation et conservation de pommes de terre' },
    { value: '1032Z', text: '1032Z - Préparation de jus de fruits et légumes' },
    { value: '1039A', text: '1039A - Autre transformation et conservation de légumes' },
    { value: '1039B', text: '1039B - Transformation et conservation de fruits' },
    { value: '1041A', text: '1041A - Fabrication d\'huiles et graisses brutes' },
    { value: '1041B', text: '1041B - Fabrication d\'huiles et graisses raffinées' },
    { value: '1042Z', text: '1042Z - Fabrication de margarine et graisses comestibles similaires' },
    { value: '1051A', text: '1051A - Fabrication de lait liquide et de produits frais' },
    { value: '1051B', text: '1051B - Fabrication de beurre' },
    { value: '1051C', text: '1051C - Fabrication de fromage' },
    { value: '1051D', text: '1051D - Fabrication d\'autres produits laitiers' },
    { value: '1052Z', text: '1052Z - Fabrication de glaces et sorbets' },
    { value: '1061A', text: '1061A - Meunerie' },
    { value: '1061B', text: '1061B - Autres activités du travail des grains' },
    { value: '1062Z', text: '1062Z - Fabrication de produits amylacés' },
    { value: '1071A', text: '1071A - Fabrication industrielle de pain et de pâtisserie fraîche' },
    { value: '1071B', text: '1071B - Cuisson de produits de boulangerie' },
    { value: '1071C', text: '1071C - Boulangerie et boulangerie-pâtisserie' },
    { value: '1071D', text: '1071D - Pâtisserie' },
    { value: '1072Z', text: '1072Z - Fabrication de biscuits, biscottes et pâtisseries de conservation' },
    { value: '1073Z', text: '1073Z - Fabrication de pâtes alimentaires' },
    { value: '1081Z', text: '1081Z - Fabrication de sucre' },
    { value: '1082Z', text: '1082Z - Fabrication de cacao, chocolat et de produits de confiserie' },
    { value: '1083Z', text: '1083Z - Transformation du thé et du café' },
    { value: '1084Z', text: '1084Z - Fabrication de condiments et assaisonnements' },
    { value: '1085Z', text: '1085Z - Fabrication de plats préparés' },
    { value: '1086Z', text: '1086Z - Fabrication d\'aliments homogénéisés et diététiques' },
    { value: '1089Z', text: '1089Z - Fabrication d\'autres produits alimentaires nca' },
    { value: '1091Z', text: '1091Z - Fabrication d\'aliments pour animaux de ferme' },
    { value: '1092Z', text: '1092Z - Fabrication d\'aliments pour animaux de compagnie' },
    { value: '1101Z', text: '1101Z - Production de boissons alcooliques distillées' },
    { value: '1102A', text: '1102A - Fabrication de vins effervescents' },
    { value: '1102B', text: '1102B - Vinification' },
    { value: '1103Z', text: '1103Z - Fabrication de cidre et de vins de fruits' },
    { value: '1104Z', text: '1104Z - Production d\'autres boissons fermentées non distillées' },
    { value: '1105Z', text: '1105Z - Fabrication de bière' },
    { value: '1106Z', text: '1106Z - Fabrication de malt' },
    { value: '1107A', text: '1107A - Industrie des eaux de table' },
    { value: '1107B', text: '1107B - Production de boissons rafraîchissantes' },
    { value: '1200Z', text: '1200Z - Fabrication de produits à base de tabac' },
    { value: '1310Z', text: '1310Z - Préparation de fibres textiles et filature' },
    { value: '1320Z', text: '1320Z - Tissage' },
    { value: '1330Z', text: '1330Z - Ennoblissement textile'},
    { value: '1391Z', text: '1391Z - Fabrication d\'étoffes à mailles' },
    { value: '1392Z', text: '1392Z -Fabrication d\'articles textiles, sauf habillement' },
    { value: '1393Z', text: '1393Z - Fabrication de tapis et moquettes' },
    { value: '1394Z', text: '1394Z - Fabrication de ficelles, cordes et filets' },
    { value: '1395Z', text: '1395Z - Fabrication de non-tissés, sauf habillement' },
    { value: '1396Z', text: '1396Z - Fabrication d\'autres textiles techniques et industriels' },
    { value: '1399Z', text: '1399Z - Fabrication d\'autres textiles n.c.a.' },
    { value: '1411Z', text: '1411Z - Fabrication de vêtements en cuir' },
    { value: '1412Z', text: '1412Z - Fabrication de vêtements de travail' },
    { value: '1413Z', text: '1413Z - Fabrication de vêtements de dessus' },
    { value: '1414Z', text: '1414Z - Fabrication de vêtements de dessous' },
    { value: '1419Z', text: '1419Z - Fabrication d\'autres vêtements et accessoires' },
    { value: '1420Z', text: '1420Z - Fabrication d\'articles en fourrure' },
    { value: '1431Z', text: '1431Z - Fabrication d\'articles chaussants à mailles' },
    { value: '1439Z', text: '1439Z - Fabrication d\'autres articles à mailles' },
    { value: '1511Z', text: '1511Z - Apprêt et tannage des cuirs ; préparation et teinture des fourrures' },
    { value: '1512Z', text: '1512Z - Fabrication d\'articles de voyage, de maroquinerie et de sellerie' },
    { value: '1520Z', text: '1520Z - Fabrication de chaussures' },
    { value: '1610A', text: '1610A - Sciage et rabotage du bois, hors imprégnation' },
    { value: '1610B', text: '1610B - Imprégnation du bois' },
    { value: '1621Z', text: '1621Z - Fabrication de placage et de panneaux de bois' },
    { value: '1622Z', text: '1622Z - Fabrication de parquets assemblés' },
    { value: '1623Z', text: '1623Z - Fabrication de charpentes et d\'autres menuiseries' },
    { value: '1624Z', text: '1624Z - Fabrication d\'emballages en bois' },
    { value: '1629Z', text: '1629Z - Fabrication d\'objets divers en bois ; fabrication d\'objets en liège, vannerie et sparterie' },
    { value: '1629Z', text: '1629Z - Fabrication d\'objets divers en bois; fabrication d\'objets en liège, vannerie et sparterie' },
    { value: '1711Z', text: '1711Z - Fabrication de pâte à papier' },
    { value: '1712Z', text: '1712Z - Fabrication de papier et de carton' },
    { value: '1721A', text: '1721A - Fabrication de carton ondulé' },
    { value: '1721B', text: '1721B - Fabrication de cartonnages' },
    { value: '1721C', text: '1721C - Fabrication d\'emballages en papier' },
    { value: '1722Z', text: '1722Z - Fabrication d\'articles en papier à usage sanitaire ou domestique' },
    { value: '1723Z', text: '1723Z - Fabrication d\'articles de papeterie' },
    { value: '1724Z', text: '1724Z - Fabrication de papiers peints' },
    { value: '1729Z', text: '1729Z - Fabrication d\'autres articles en papier ou en carton' },
    { value: '1811Z', text: '1811Z - Imprimerie de journaux' },
    { value: '1812Z', text: '1812Z - Autre imprimerie (labeur)' },
    { value: '1813Z', text: '1813Z - Activités de pré-presse' },
    { value: '1814Z', text: '1814Z - Reliure et activités connexes' },
    { value: '1820Z', text: '1820Z - Reproduction d\'enregistrements' },
    { value: '1910Z', text: '1910Z - Cokéfaction' },
    { value: '1920Z', text: '1920Z - Raffinage du pétrole' },
    { value: '2011Z', text: '2011Z - Fabrication de gaz industriels' },
    { value: '2012Z', text: '2012Z - Fabrication de colorants et de pigments' },
    { value: '2013A', text: '2013A - Enrichissement et retraitement de matières nucléaires' },
    { value: '2013B', text: '2013B - Fabrication d\'autres produits chimiques inorganiques de base nca' },
    { value: '2014Z', text: '2014Z - Fabrication d\'autres produits chimiques organiques de base' },
    { value: '2015Z', text: '2015Z - Fabrication de produits azotés et d\'engrais' },
    { value: '2016Z', text: '2016Z - Fabrication de matières plastiques de base' },
    { value: '2017Z', text: '2017Z - Fabrication de caoutchouc synthétique' },
    { value: '2020Z', text: '2020Z - Fabrication de pesticides et d\'autres produits agrochimiques' },
    { value: '2030Z', text: '2030Z - Fabrication de peintures, vernis, encres et mastics' },
    { value: '2041Z', text: '2041Z - Fabrication de savons, détergents et produits d\'entretien' },
    { value: '2042Z', text: '2042Z - Fabrication de parfums et de produits pour la toilette' },
    { value: '2051Z', text: '2051Z - Fabrication de produits explosifs' },
    { value: '2052Z', text: '2052Z - Fabrication de colles' },
    { value: '2053Z', text: '2053Z - Fabrication d\'huiles essentielles' },
    { value: '2059Z', text: '2059Z - Fabrication d\'autres produits chimiques nca' },
    { value: '2060Z', text: '2060Z - Fabrication de fibres artificielles ou synthétiques' },
    { value: '2110Z', text: '2110Z - Fabrication de produits pharmaceutiques de base' },
    { value: '2120Z', text: '2120Z - Fabrication de préparations pharmaceutiques' },
    { value: '2211Z', text: '2211Z - Fabrication et rechapage de pneumatiques' },
    { value: '2219Z', text: '2219Z - Fabrication d\'autres articles en caoutchouc' },
    { value: '2221Z', text: '2221Z - Fabrication de plaques, feuilles, tubes et profilés en matières plastiques' },
    { value: '2222Z', text: '2222Z - Fabrication d\'emballages en matières plastiques' },
    { value: '2223Z', text: '2223Z - Fabrication d\'éléments en matières plastiques pour la construction' },
    { value: '2229A', text: '2229A - Fabrication de pièces techniques à base de matières plastiques' },
    { value: '2229B', text: '2229B - Fabrication de produits de consommation courante en matières plastiques' },
    { value: '2311Z', text: '2311Z - Fabrication de verre plat' },
    { value: '2312Z', text: '2312Z - Façonnage et transformation du verre plat' },
    { value: '2313Z', text: '2313Z - Fabrication de verre creux' },
    { value: '2314Z', text: '2314Z - Fabrication de fibres de verre' },
    { value: '2319Z', text: '2319Z - Fabrication et façonnage d\'autres articles en verre, y compris verre technique' },
    { value: '2320Z', text: '2320Z - Fabrication de produits réfractaires' },
    { value: '2331Z', text: '2331Z - Fabrication de carreaux en céramique' },
    { value: '2332Z', text: '2332Z - Fabrication de briques, tuiles et produits de construction, en terre cuite' },
    { value: '2341Z', text: '2341Z - Fabrication d\'articles céramiques à usage domestique ou ornemental' },
    { value: '2342Z', text: '2342Z - Fabrication d\'appareils sanitaires en céramique' },
    { value: '2343Z', text: '2343Z - Fabrication d\'isolateurs et pièces isolantes en céramique' },
    { value: '2344Z', text: '2344Z - Fabrication d\'autres produits céramiques à usage technique' },
    { value: '2349Z', text: '2349Z - Fabrication d\'autres produits céramiques' },
    { value: '2351Z', text: '2351Z - Fabrication de ciment' },
    { value: '2352Z', text: '2352Z - Fabrication de chaux et plâtre' },
    { value: '2361Z', text: '2361Z - Fabrication d\'éléments en béton pour la construction' },
    { value: '2362Z', text: '2362Z - Fabrication d\'éléments en plâtre pour la construction' },
    { value: '2363Z', text: '2363Z - Fabrication de béton prêt à l\'emploi' },
    { value: '2364Z', text: '2364Z - Fabrication de mortiers et bétons secs' },
    { value: '2365Z', text: '2365Z - Fabrication d\'ouvrages en fibre-ciment' },
    { value: '2369Z', text: '2369Z - Fabrication d\'autres ouvrages en béton, en ciment ou en plâtre' },
    { value: '2370Z', text: '2370Z - Taille, façonnage et finissage de pierres' },
    { value: '2391Z', text: '2391Z - Fabrication de produits abrasifs' },
    { value: '2399Z', text: '2399Z - Fabrication d\'autres produits minéraux non métalliques nca' },
    { value: '2410Z', text: '2410Z - Sidérurgie' },
    { value: '2420Z', text: '2420Z - Fabrication de tubes, tuyaux, profilés creux et accessoires correspondants en acier' },
    { value: '2431Z', text: '2431Z - Étirage à froid de barres' },
    { value: '2432Z', text: '2432Z - Laminage à froid de feuillards' },
    { value: '2433Z', text: '2433Z - Profilage à froid par formage ou pliage' },
    { value: '2434Z', text: '2434Z - Tréfilage à froid' },
    { value: '2441Z', text: '2441Z - Production de métaux précieux' },
    { value: '2442Z', text: '2442Z - Métallurgie de l\'aluminium' },
    { value: '2443Z', text: '2443Z - Métallurgie du plomb, du zinc ou de l\'étain' },
    { value: '2444Z', text: '2444Z - Métallurgie du cuivre' },
    { value: '2445Z', text: '2445Z - Métallurgie des autres métaux non ferreux' },
    { value: '2446Z', text: '2446Z - Élaboration et transformation de matières nucléaires' },
    { value: '2451Z', text: '2451Z - Fonderie de fonte' },
    { value: '2452Z', text: '2452Z - Fonderie d\'acier' },
    { value: '2453Z', text: '2453Z - Fonderie de métaux légers' },
    { value: '2454Z', text: '2454Z - Fonderie d\'autres métaux non ferreux' },
    { value: '2511Z', text: '2511Z - Fabrication de structures métalliques et de parties de structures' },
    { value: '2512Z', text: '2512Z - Fabrication de portes et fenêtres en métal' },
    { value: '2521Z', text: '2521Z - Fabrication de radiateurs et de chaudières pour le chauffage central' },
    { value: '2529Z', text: '2529Z - Fabrication d\'autres réservoirs, citernes et conteneurs métalliques' },
    { value: '2530Z', text: '2530Z - Fabrication de générateurs de vapeur, à l\'exception des chaudières pour le chauffage central' },
    { value: '2540Z', text: '2540Z - Fabrication d\'armes et de munitions' },
    { value: '2550A', text: '2550A - Forge, estampage, matriçage ; métallurgie des poudres' },
    { value: '2550B', text: '2550B - Découpage, emboutissage' },
    { value: '2561Z', text: '2561Z - Traitement et revêtement des métaux' },
    { value: '2562A', text: '2562A - Décolletage' },
    { value: '2562B', text: '2562B - Mécanique industrielle' },
    { value: '2571Z', text: '2571Z - Fabrication de coutellerie' },
    { value: '2572Z', text: '2572Z - Fabrication de serrures et de ferrures' },
    { value: '2573A', text: '2573A - Fabrication de moules et modèles' },
    { value: '2573B', text: '2573B - Fabrication d\'autres outillages' },
    { value: '2591Z', text: '2591Z - Fabrication de fûts et emballages métalliques similaires' },
    { value: '2592Z', text: '2592Z - Fabrication d\'emballages métalliques légers' },
    { value: '2593Z', text: '2593Z - Fabrication d\'articles en fils métalliques, de chaînes et de ressorts' },
    { value: '2594Z', text: '2594Z - Fabrication de vis et de boulons' },
    { value: '2599A', text: '2599A - Fabrication d\'articles métalliques ménagers' },
    { value: '2599B', text: '2599B - Fabrication d\'autres articles métalliques' },
    { value: '2611Z', text: '2611Z - Fabrication de composants électroniques' },
    { value: '2612Z', text: '2612Z - Fabrication de cartes électroniques assemblées' },
    { value: '2620Z', text: '2620Z - Fabrication d\'ordinateurs et d\'équipements périphériques' },
    { value: '2630Z', text: '2630Z - Fabrication d\'équipements de communication' },
    { value: '2640Z', text: '2640Z - Fabrication de produits électroniques grand public' },
    { value: '2651A', text: '2651A - Fabrication d\'équipements d\'aide à la navigation' },
    { value: '2651B', text: '2651B - Fabrication d\'instrumentation scientifique et technique' },
    { value: '2652Z', text: '2652Z - Horlogerie' },
    { value: '2660Z', text: '2660Z - Fabrication d\'équipements d\'irradiation médicale, d\'équipements électromédicaux et électrothérapeutiques' },
    { value: '2670Z', text: '2670Z - Fabrication de matériels optique et photographique' },
    { value: '2680Z', text: '2680Z - Fabrication de supports magnétiques et optiques' },
    { value: '2711Z', text: '2711Z - Fabrication de moteurs, génératrices et transformateurs électriques' },
    { value: '2712Z', text: '2712Z - Fabrication de matériel de distribution et de commande électrique' },
    { value: '2720Z', text: '2720Z - Fabrication de piles et d\'accumulateurs électriques' },
    { value: '2731Z', text: '2731Z - Fabrication de câbles de fibres optiques' },
    { value: '2732Z', text: '2732Z - Fabrication d\'autres fils et câbles électroniques ou électriques' },
    { value: '2733Z', text: '2733Z - Fabrication de matériel d\'installation électrique' },
    { value: '2740Z', text: '2740Z - Fabrication d\'appareils d\'éclairage électrique' },
    { value: '2751Z', text: '2751Z - Fabrication d\'appareils électroménagers' },
    { value: '2752Z', text: '2752Z - Fabrication d\'appareils ménagers non électriques' },
    { value: '2790Z', text: '2790Z - Fabrication d\'autres matériels électriques' },
    { value: '2811Z', text: '2811Z - Fabrication de moteurs et turbines, à l\'exception des moteurs d\'avions et de véhicules' },
    { value: '2812Z', text: '2812Z - Fabrication d\'équipements hydrauliques et pneumatiques' },
    { value: '2813Z', text: '2813Z - Fabrication d\'autres pompes et compresseurs' },
    { value: '2814Z', text: '2814Z - Fabrication d\'autres articles de robinetterie' },
    { value: '2815Z', text: '2815Z - Fabrication d\'engrenages et d\'organes mécaniques de transmission' },
    { value: '2821Z', text: '2821Z - Fabrication de fours et brûleurs' },
    { value: '2822Z', text: '2822Z - Fabrication de matériel de levage et de manutention' },
    { value: '2823Z', text: '2823Z - Fabrication de machines et d\'équipements de bureau (à l\'exception des ordinateurs et équipements périphériques)' },
    { value: '2824Z', text: '2824Z - Fabrication d\'outillage portatif à moteur incorporé' },
    { value: '2825Z', text: '2825Z - Fabrication d\'équipements aérauliques et frigorifiques industriels' },
    { value: '2829A', text: '2829A - Fabrication d\'équipements d\'emballage, de conditionnement et de pesage' },
    { value: '2829B', text: '2829B - Fabrication d\'autres machines d\'usage général' },
    { value: '2830Z', text: '2830Z - Fabrication de machines agricoles et forestières' },
    { value: '2841Z', text: '2841Z - Fabrication de machines-outils pour le travail des métaux' },
    { value: '2849Z', text: '2849Z - Fabrication d\'autres machines-outils' },
    { value: '2891Z', text: '2891Z - Fabrication de machines pour la métallurgie' },
    { value: '2892Z', text: '2892Z - Fabrication de machines pour l\'extraction ou la construction' },
    { value: '2893Z', text: '2893Z - Fabrication de machines pour l\'industrie agro-alimentaire' },
    { value: '2894Z', text: '2894Z - Fabrication de machines pour les industries textiles' },
    { value: '2895Z', text: '2895Z - Fabrication de machines pour les industries du papier et du carton' },
    { value: '2896Z', text: '2896Z - Fabrication de machines pour le travail du caoutchouc ou des plastiques' },
    { value: '2899A', text: '2899A - Fabrication de machines d\'imprimerie' },
    { value: '2899B', text: '2899B - Fabrication d\'autres machines spécialisées' },
    { value: '2910Z', text: '2910Z - Construction de véhicules automobiles' },
    { value: '2920Z', text: '2920Z - Fabrication de carrosseries et remorques' },
    { value: '2931Z', text: '2931Z - Fabrication d\'équipements électriques et électroniques automobiles' },
    { value: '2932Z', text: '2932Z - Fabrication d\'autres équipements automobiles' },
    { value: '3011Z', text: '3011Z - Construction de navires et de structures flottantes' },
    { value: '3012Z', text: '3012Z - Construction de bateaux de plaisance' },
    { value: '3020Z', text: '3020Z - Construction de locomotives et d\'autre matériel ferroviaire roulant' },
    { value: '3030Z', text: '3030Z - Construction aéronautique et spatiale' },
    { value: '3040Z', text: '3040Z - Construction de véhicules militaires de combat' },
    { value: '3091Z', text: '3091Z - Fabrication de motocycles' },
    { value: '3092Z', text: '3092Z - Fabrication de bicyclettes et de véhicules pour invalides' },
    { value: '3099Z', text: '3099Z - Fabrication d\'autres équipements de transport nca' },
    { value: '3101Z', text: '3101Z - Fabrication de meubles de bureau et de magasin' },
    { value: '3102Z', text: '3102Z - Fabrication de meubles de cuisine' },
    { value: '3103Z', text: '3103Z - Fabrication de matelas' },
    { value: '3109A', text: '3109A - Fabrication de sièges d\'ameublement d\'intérieur' },
    { value: '3109B', text: '3109B - Fabrication d\'autres meubles et industries connexes de l\'ameublement' },
    { value: '3211Z', text: '3211Z - Frappe de monnaie' },
    { value: '3212Z', text: '3212Z - Fabrication d\'articles de joaillerie et bijouterie' },
    { value: '3213Z', text: '3213Z - Fabrication d\'articles de bijouterie fantaisie et articles similaires' },
    { value: '3220Z', text: '3220Z - Fabrication d\'instruments de musique' },
    { value: '3230Z', text: '3230Z - Fabrication d\'articles de sport' },
    { value: '3240Z', text: '3240Z - Fabrication de jeux et jouets' },
    { value: '3250A', text: '3250A - Fabrication de matériel chirurgical et dentaire' },
    { value: '3250A', text: '3250A - Fabrication de matériel médico-chirurgical et dentaire' },
    { value: '3250A', text: '3250A - Fabrication de matériels médico-chirurgical et dentaire' },
    { value: '3250B', text: '3250B - Fabrication de lunettes' },
    { value: '3291Z', text: '3291Z - Fabrication d\'articles de brosserie' },
    { value: '3299Z', text: '3299Z - Autres activités manufacturières nca' },
    { value: '3311Z', text: '3311Z - Réparation d\'ouvrages en métaux' },
    { value: '3312Z', text: '3312Z - Réparation de machines et équipements mécaniques' },
    { value: '3313Z', text: '3313Z - Réparation de matériels électroniques et optiques' },
    { value: '3314Z', text: '3314Z - Réparation d\'équipements électriques' },
    { value: '3315Z', text: '3315Z - Réparation et maintenance navale' },
    { value: '3316Z', text: '3316Z - Réparation et maintenance d\'aéronefs et d\'engins spatiaux' },
    { value: '3317Z', text: '3317Z - Réparation et maintenance d\'autres équipements de transport' },
    { value: '3319Z', text: '3319Z - Réparation d\'autres équipements' },
    { value: '3320A', text: '3320A - Installation de structures métalliques, chaudronnées et de tuyauterie' },
    { value: '3320B', text: '3320B - Installation de machines et équipements mécaniques' },
    { value: '3320C', text: '3320C - Conception d\'ensemble et assemblage sur site industriel d\'équipements de contrôle des processus industriels' },
    { value: '3320D', text: '3320D - Installation d\'équipements électriques, de matériels électroniques et optiques ou d\'autres matériels' },
    { value: '3511Z', text: '3511Z - Production d\'électricité' },
    { value: '3512Z', text: '3512Z - Transport d\'électricité' },
    { value: '3513Z', text: '3513Z - Distribution d\'électricité' },
    { value: '3514Z', text: '3514Z - Commerce d\'électricité' },
    { value: '3521Z', text: '3521Z - Production de combustibles gazeux' },
    { value: '3522Z', text: '3522Z - Distribution de combustibles gazeux par conduites' },
    { value: '3523Z', text: '3523Z - Commerce de combustibles gazeux par conduites' },
    { value: '3530Z', text: '3530Z - Production et distribution de vapeur et d\'air conditionné' },
    { value: '3600Z', text: '3600Z - Captage, traitement et distribution d\'eau' },
    { value: '3700Z', text: '3700Z - Collecte et traitement des eaux usées' },
    { value: '3811Z', text: '3811Z - Collecte des déchets non dangereux' },
    { value: '3812Z', text: '3812Z - Collecte des déchets dangereux' },
    { value: '3821Z', text: '3821Z - Traitement et élimination des déchets non dangereux' },
    { value: '3822Z', text: '3822Z - Traitement et élimination des déchets dangereux' },
    { value: '3831Z', text: '3831Z - Démantèlement d\'épaves' },
    { value: '3832Z', text: '3832Z - Récupération de déchets triés' },
    { value: '3900Z', text: '3900Z - Dépollution et autres services de gestion des déchets' },
    { value: '4110A', text: '4110A - Promotion immobilière de logements' },
    { value: '4110B', text: '4110B - Promotion immobilière de bureaux' },
    { value: '4110C', text: '4110C - Promotion immobilière d\'autres bâtiments' },
    { value: '4110D', text: '4110D - Supports juridiques de programmes' },
    { value: '4120A', text: '4120A - Construction de maisons individuelles' },
    { value: '4120B', text: '4120B - Construction d\'autres bâtiments' },
    { value: '4211Z', text: '4211Z - Construction de routes et autoroutes' },
    { value: '4212Z', text: '4212Z - Construction de voies ferrées de surface et souterraines' },
    { value: '4213A', text: '4213A - Construction d\'ouvrages d\'art' },
    { value: '4213B', text: '4213B - Construction et entretien de tunnels' },
    { value: '4221Z', text: '4221Z - Construction de réseaux pour fluides' },
    { value: '4222Z', text: '4222Z - Construction de réseaux électriques et de télécommunications' },
    { value: '4291Z', text: '4291Z - Construction d\'ouvrages maritimes et fluviaux' },
    { value: '4299Z', text: '4299Z - Construction d\'autres ouvrages de génie civil nca' },
    { value: '4311Z', text: '4311Z - Travaux de démolition' },
    { value: '4312A', text: '4312A - Travaux de terrassement courants et travaux préparatoires' },
    { value: '4312B', text: '4312B - Travaux de terrassement spécialisés ou de grande masse' },
    { value: '4313Z', text: '4313Z - Forages et sondages' },
    { value: '4321A', text: '4321A - Travaux d\'installation électrique dans tous locaux' },
    { value: '4321B', text: '4321B - Travaux d\'installation électrique sur la voie publique' },
    { value: '4322A', text: '4322A - Travaux d\'installation d\'eau et de gaz en tous locaux' },
    { value: '4322B', text: '4322B - Travaux d\'installation d\'équipements thermiques et de climatisation' },
    { value: '4329A', text: '4329A - Travaux d\'isolation' },
    { value: '4329B', text: '4329B - Autres travaux d\'installation nca' },
    { value: '4331Z', text: '4331Z - Travaux de plâtrerie' },
    { value: '4332A', text: '4332A - Travaux de menuiserie bois et PVC' },
    { value: '4332B', text: '4332B - Travaux de menuiserie métallique et serrurerie' },
    { value: '4332C', text: '4332C - Agencement de lieux de vente' },
    { value: '4333Z', text: '4333Z - Travaux de revêtement des sols et des murs' },
    { value: '4334Z', text: '4334Z - Travaux de peinture et vitrerie' },
    { value: '4339Z', text: '4339Z - Autres travaux de finition' },
    { value: '4391A', text: '4391A - Travaux de charpente' },
    { value: '4391B', text: '4391B - Travaux de couverture par éléments' },
    { value: '4399A', text: '4399A - Travaux d\'étanchéification' },
    { value: '4399B', text: '4399B - Travaux de montage de structures métalliques' },
    { value: '4399C', text: '4399C - Travaux de maçonnerie générale et gros œuvre de bâtiment' },
    { value: '4399D', text: '4399D - Autres travaux spécialisés de construction' },
    { value: '4399E', text: '4399E - Location avec opérateur de matériel de construction' },
    { value: '4511Z', text: '4511Z - Commerce de voitures et de véhicules automobiles légers' },
    { value: '4519Z', text: '4519Z - Commerce d\'autres véhicules automobiles' },
    { value: '4520A', text: '4520A - Entretien et réparation de véhicules automobiles légers' },
    { value: '4520B', text: '4520B - Entretien et réparation d\'autres véhicules automobiles' },
    { value: '4531Z', text: '4531Z - Commerce de gros d\'équipements automobiles' },
    { value: '4532Z', text: '4532Z - Commerce de détail d\'équipements automobiles' },
    { value: '4540Z', text: '4540Z - Commerce et réparation de motocycles' },
    { value: '4611Z', text: '4611Z - Intermédiaires du commerce en matières premières agricoles, animaux vivants, matières premières textiles et produits semi-finis' },
    { value: '4612A', text: '4612A - Centrales d\'achat de carburant' },
    { value: '4612B', text: '4612B - Autres intermédiaires du commerce en combustibles, métaux, minéraux et produits chimiques' },
    { value: '4613Z', text: '4613Z - Intermédiaires du commerce en bois et matériaux de construction' },
    { value: '4614Z', text: '4614Z - Intermédiaires du commerce en machines, équipements industriels, navires et avions' },
    { value: '4615Z', text: '4615Z - Intermédiaires du commerce en meubles, articles de ménage et quincaillerie' },
    { value: '4616Z', text: '4616Z -Intermédiaires du commerce en textiles, habillement, fourrures, chaussures et articles en cuir' },
    { value: '4617A', text: '4617A - Centrales d\'achat alimentaires' },
    { value: '4617B', text: '4617B - Autres intermédiaires du commerce en denrées, boissons et tabac' },
    { value: '4618Z', text: '4618Z - Intermédiaires spécialisés dans le commerce d\'autres produits spécifiques' },
    { value: '4619A', text: '4619A - Centrales d\'achat non alimentaires' },
    { value: '4619B', text: '4619B - Autres intermédiaires du commerce en produits divers' },
    { value: '4621Z', text: '4621Z - Commerce de gros (commerce interentreprises) de céréales, de tabac non manufacturé, de semences et d\'aliments pour le bétail' },
    { value: '4622Z', text: '4622Z - Commerce de gros (commerce interentreprises) de fleurs et plantes' },
    { value: '4623Z', text: '4623Z - Commerce de gros (commerce interentreprises) d\'animaux vivants' },
    { value: '4624Z', text: '4624Z - Commerce de gros (commerce interentreprises) de cuirs et peaux' },
    { value: '4631Z', text: '4631Z - Commerce de gros (commerce interentreprises) de fruits et légumes' },
    { value: '4632A', text: '4632A - Commerce de gros (commerce interentreprises) de viandes de boucherie' },
    { value: '4632B', text: '4632B - Commerce de gros (commerce interentreprises) de produits à base de viande' },
    { value: '4632C', text: '4632C - Commerce de gros (commerce interentreprises) de volailles et gibier' },
    { value: '4633Z', text: '4633Z - Commerce de gros (commerce interentreprises) de produits laitiers, œufs, huiles et matières grasses comestibles' },
    { value: '4634Z', text: '4634Z - Commerce de gros (commerce interentreprises) de boissons' },
    { value: '4635Z', text: '4635Z - Commerce de gros (commerce interentreprises) de produits à base de tabac' },
    { value: '4636Z', text: '4636Z - Commerce de gros (commerce interentreprises) de sucre, chocolat et confiserie' },
    { value: '4637Z', text: '4637Z - Commerce de gros (commerce interentreprises) de café, thé, cacao et épices' },
    { value: '4638A', text: '4638A - Commerce de gros (commerce interentreprises) de poissons, crustacés et mollusques' },
    { value: '4638B', text: '4638B - Commerce de gros (commerce interentreprises) alimentaire spécialisé divers' },
    { value: '4639A', text: '4639A - Commerce de gros (commerce interentreprises) de produits surgelés' },
    { value: '4639B', text: '4639B - Commerce de gros (commerce interentreprises) alimentaire non spécialisé' },
    { value: '4641Z', text: '4641Z - Commerce de gros de textiles' },
    { value: '4642Z', text: '4642Z - Commerce de gros (commerce interentreprises) d\'habillement et de chaussures' },
    { value: '4643Z', text: '4643Z - Commerce de gros (commerce interentreprises) d\'appareils électroménagers' },
    { value: '4644Z', text: '4644Z - Commerce de gros (commerce interentreprises) de vaisselle, verrerie et produits d\'entretien' },
    { value: '4645Z', text: '4645Z - Commerce de gros (commerce interentreprises) de parfumerie et de produits de beauté' },
    { value: '4646Z', text: '4646Z - Commerce de gros (commerce interentreprises) de produits pharmaceutiques' },
    { value: '4647Z', text: '4647Z - Commerce de gros (commerce interentreprises) de meubles, de tapis et d\'appareils d\'éclairage' },
    { value: '4648Z', text: '4648Z - Commerce de gros (commerce interentreprises) d\'articles d\'horlogerie et de bijouterie' },
    { value: '4649Z', text: '4649Z - Commerce de gros (commerce interentreprises) d\'autres biens domestiques' },
    { value: '4651Z', text: '4651Z - Commerce de gros (commerce interentreprises) d\'ordinateurs, d\'équipements informatiques périphériques et de logiciels' },
    { value: '4652Z', text: '4652Z - Commerce de gros (commerce interentreprises) de composants et d\'équipements électroniques et de télécommunication' },
    { value: '4661Z', text: '4661Z - Commerce de gros (commerce interentreprises) de matériel agricole' },
    { value: '4662Z', text: '4662Z - Commerce de gros (commerce interentreprises) de machines-outils' },
    { value: '4663Z', text: '4663Z - Commerce de gros (commerce interentreprises) de machines pour l\'extraction, la construction et le génie civil' },
    { value: '4664Z', text: '4664Z - Commerce de gros de machines pour l\'industrie textile et l\'habillement' },
    { value: '4665Z', text: '4665Z - Commerce de gros (commerce interentreprises) de mobilier de bureau' },
    { value: '4666Z', text: '4666Z - Commerce de gros (commerce interentreprises) d\'autres machines et équipements de bureau' },
    { value: '4669A', text: '4669A - Commerce de gros (commerce interentreprises) de matériel électrique' },
    { value: '4669B', text: '4669B - Commerce de gros (commerce interentreprises) de fournitures et équipements industriels divers' },
    { value: '4669C', text: '4669C - Commerce de gros (commerce interentreprises) de fournitures et équipements divers pour le commerce et les services' },
    { value: '4671Z', text: '4671Z - Commerce de gros (commerce interentreprises) de combustibles et de produits annexes' },
    { value: '4672Z', text: '4672Z - Commerce de gros (commerce interentreprises) de minerais et métaux' },
    { value: '4673A', text: '4673A - Commerce de gros (commerce interentreprises) de bois et de matériaux de construction' },
    { value: '4673B', text: '4673B - Commerce de gros (commerce interentreprises) d\'appareils sanitaires et de produits de décoration' },
    { value: '4674A', text: '4674A - Commerce de gros (commerce interentreprises) de quincaillerie' },
    { value: '4674B', text: '4674B - Commerce de gros (commerce interentreprises) de fournitures pour la plomberie et le chauffage' },
    { value: '4675Z', text: '4675Z - Commerce de gros (commerce interentreprises) de produits chimiques' },
    { value: '4676Z', text: '4676Z - Commerce de gros (commerce interentreprises) d\'autres produits intermédiaires' },
    { value: '4677Z', text: '4677Z - Commerce de gros (commerce interentreprises) de déchets et débris' },
    { value: '4690Z', text: '4690Z - Commerce de gros (commerce interentreprises) non spécialisé' },
    { value: '4711A', text: '4711A - Commerce de détail de produits surgelés' },
    { value: '4711B', text: '4711B - Commerce d\'alimentation générale' },
    { value: '4711C', text: '4711C - Supérettes' },
    { value: '4711D', text: '4711D - Supermarchés' },
    { value: '4711E', text: '4711E - Magasins multi-commerces' },
    { value: '4711F', text: '4711F - Hypermarchés' },
    { value: '4719A', text: '4719A - Grands magasins' },
    { value: '4719B', text: '4719B - Autres commerces de détail en magasin non spécialisé' },
    { value: '4721Z', text: '4721Z - Commerce de détail de fruits et légumes en magasin spécialisé' },
    { value: '4722Z', text: '4722Z - Commerce de détail de viandes et de produits à base de viande en magasin spécialisé' },
    { value: '4723Z', text: '4723Z - Commerce de détail de poissons, crustacés et mollusques en magasin spécialisé' },
    { value: '4724Z', text: '4724Z - Commerce de détail de pain, pâtisserie et confiserie en magasin spécialisé' },
    { value: '4725Z', text: '4725Z - Commerce de détail de boissons en magasin spécialisé' },
    { value: '4726Z', text: '4726Z - Commerce de détail de produits à base de tabac en magasin spécialisé' },
    { value: '4729Z', text: '4729Z - Autres commerces de détail alimentaires en magasin spécialisé' },
    { value: '4730Z', text: '4730Z - Commerce de détail de carburants en magasin spécialisé' },
    { value: '4741Z', text: '4741Z - Commerce de détail d\'ordinateurs, d\'unités périphériques et de logiciels en magasin spécialisé' },
    { value: '4742Z', text: '4742Z - Commerce de détail de matériels de télécommunication en magasin spécialisé' },
    { value: '4743Z', text: '4743Z - Commerce de détail de matériels audio et vidéo en magasin spécialisé' },
    { value: '4751Z', text: '4751Z - Commerce de détail de textiles en magasin spécialisé' },
    { value: '4752A', text: '4752A - Commerce de détail de quincaillerie, peintures et verres en petites surfaces (moins de 400 m2)' },
    { value: '4752B', text: '4752B - Commerce de détail de quincaillerie, peintures et verres en grandes surfaces (400 m2 et plus)' },
    { value: '4753Z', text: '4753Z - Commerce de détail de tapis, moquettes et revêtements de murs et de sols en magasin spécialisé' },
    { value: '4754Z', text: '4754Z - Commerce de détail d\'appareils électroménagers en magasin spécialisé' },
    { value: '4759A', text: '4759A - Commerce de détail de meubles' },
    { value: '4759B', text: '4759B - Commerce de détail d\'autres équipements du foyer' },
    { value: '4761Z', text: '4761Z - Commerce de détail de livres en magasin spécialisé' },
    { value: '4762Z', text: '4762Z - Commerce de détail de journaux et papeterie en magasin spécialisé' },
    { value: '4763Z', text: '4763Z - Commerce de détail d\'enregistrements musicaux et vidéo en magasin spécialisé' },
    { value: '4764Z', text: '4764Z - Commerce de détail d\'articles de sport en magasin spécialisé' },
    { value: '4765Z', text: '4765Z - Commerce de détail de jeux et jouets en magasin spécialisé' },
    { value: '4771Z', text: '4771Z - Commerce de détail d\'habillement en magasin spécialisé' },
    { value: '4772A', text: '4772A - Commerce de détail de la chaussure' },
    { value: '4772B', text: '4772B - Commerce de détail de maroquinerie et d\'articles de voyage' },
    { value: '4773Z', text: '4773Z - Commerce de détail de produits pharmaceutiques en magasin spécialisé' },
    { value: '4774Z', text: '4774Z - Commerce de détail d\'articles médicaux et orthopédiques en magasin spécialisé' },
    { value: '4775Z', text: '4775Z - Commerce de détail de parfumerie et de produits de beauté en magasin spécialisé' },
    { value: '4776Z', text: '4776Z - Commerce de détail de fleurs, plantes, graines, engrais, animaux de compagnie et aliments pour ces animaux en magasin spécialisé' },
    { value: '4777Z', text: '4777Z - Commerce de détail d\'articles d\'horlogerie et de bijouterie en magasin spécialisé' },
    { value: '4778A', text: '4778A - Commerces de détail d\'optique' },
    { value: '4778B', text: '4778B - Commerces de détail de charbons et combustibles' },
    { value: '4778C', text: '4778C - Autres commerces de détail spécialisés divers' },
    { value: '4779Z', text: '4779Z - Commerce de détail de biens d\'occasion en magasin' },
    { value: '4781Z', text: '4781Z - Commerce de détail alimentaire sur éventaires et marchés' },
    { value: '4782Z', text: '4782Z - Commerce de détail de textiles, d\'habillement et de chaussures sur éventaires et marchés' },
    { value: '4789Z', text: '4789Z - Autres commerces de détail sur éventaires et marchés' },
    { value: '4791A', text: '4791A - Vente à distance sur catalogue général' },
    { value: '4791B', text: '4791B - Vente à distance sur catalogue spécialisé' },
    { value: '4799A', text: '4799A - Vente à domicile' },
    { value: '4799B', text: '4799B - Vente par automates et autres commerces de détail hors magasin, éventaires ou marchés nca' },
    { value: '4910Z', text: '4910Z - Transport ferroviaire interurbain de voyageurs' },
    { value: '4920Z', text: '4920Z - Transports ferroviaires de fret' },
    { value: '4931Z', text: '4931Z - Transports urbains et suburbains de voyageurs' },
    { value: '4932Z', text: '4932Z - Transports de voyageurs par taxis' },
    { value: '4939A', text: '4939A - Transports routiers réguliers de voyageurs' },
    { value: '4939B', text: '4939B - Autres transports routiers de voyageurs' },
    { value: '4939C', text: '4939C - Téléphériques et remontées mécaniques' },
    { value: '4941A', text: '4941A - Transports routiers de fret interurbains' },
    { value: '4941B', text: '4941B - Transports routiers de fret de proximité' },
    { value: '4941C', text: '4941C - Location de camions avec chauffeur' },
    { value: '4942Z', text: '4942Z - Services de déménagement' },
    { value: '4950Z', text: '4950Z - Transports par conduites' },
    { value: '5010Z', text: '5010Z - Transports maritimes et côtiers de passagers' },
    { value: '5020Z', text: '5020Z - Transports maritimes et côtiers de fret' },
    { value: '5030Z', text: '5030Z - Transports fluviaux de passagers' },
    { value: '5040Z', text: '5040Z - Transports fluviaux de fret' },
    { value: '5110Z', text: '5110Z - Transports aériens de passagers' },
    { value: '5121Z', text: '5121Z - Transports aériens de fret' },
    { value: '5122Z', text: '5122Z - Transports spatiaux' },
    { value: '5210A', text: '5210A - Entreposage et stockage frigorifique' },
    { value: '5210B', text: '5210B - Entreposage et stockage non frigorifique' },
    { value: '5221Z', text: '5221Z - Services auxiliaires des transports terrestres' },
    { value: '5222Z', text: '5222Z - Services auxiliaires des transports par eau' },
    { value: '5223Z', text: '5223Z - Services auxiliaires des transports aériens' },
    { value: '5224A', text: '5224A - Manutention portuaire' },
    { value: '5224B', text: '5224B - Manutention non portuaire' },
    { value: '5229A', text: '5229A - Messagerie, fret express' },
    { value: '5229B', text: '5229B - Affrètement et organisation des transports' },
    { value: '5310Z', text: '5310Z - Activités de poste dans le cadre d\'une obligation de service universel' },
    { value: '5320Z', text: '5320Z - Autres activités de poste et de courrier' },
    { value: '5510Z', text: '5510Z - Hôtels et hébergement similaire' },
    { value: '5520Z', text: '5520Z - Hébergement touristique et autre hébergement de courte durée' },
    { value: '5530Z', text: '5530Z - Terrains de camping et parcs pour caravanes ou véhicules de loisirs' },
    { value: '5590Z', text: '5590Z - Autres hébergements' },
    { value: '5610A', text: '5610A - Restauration traditionnelle' },
    { value: '5610B', text: '5610B - Cafétérias et autres libres-services' },
    { value: '5610C', text: '5610C - Restauration de type rapide' },
    { value: '5621Z', text: '5621Z - Services des traiteurs' },
    { value: '5629A', text: '5629A - Restauration collective sous contrat' },
    { value: '5629B', text: '5629B - Autres services de restauration nca' },
    { value: '5630Z', text: '5630Z - Débits de boissons' },
    { value: '5811Z', text: '5811Z - Édition de livres' },
    { value: '5812Z', text: '5812Z - Édition de répertoires et de fichiers d\'adresses' },
    { value: '5813Z', text: '5813Z - Édition de journaux' },
    { value: '5814Z', text: '5814Z - Édition de revues et périodiques' },
    { value: '5819Z', text: '5819Z - Autres activités d\'édition' },
    { value: '5821Z', text: '5821Z - Édition de jeux électroniques' },
    { value: '5829A', text: '5829A - Édition de logiciels système et de réseau' },
    { value: '5829B', text: '5829B - Edition de logiciels outils de développement et de langages' },
    { value: '5829C', text: '5829C - Edition de logiciels applicatifs' },
    { value: '5911A', text: '5911A - Production de films et de programmes pour la télévision' },
    { value: '5911B', text: '5911B - Production de films institutionnels et publicitaires' },
    { value: '5911C', text: '5911C - Production de films pour le cinéma' },
    { value: '5912Z', text: '5912Z - Post-production de films cinématographiques, de vidéo et de programmes de télévision' },
    { value: '5913A', text: '5913A - Distribution de films cinématographiques' },
    { value: '5913B', text: '5913B - Edition et distribution vidéo' },
    { value: '5914Z', text: '5914Z - Projection de films cinématographiques' },
    { value: '5920Z', text: '5920Z - Enregistrement sonore et édition musicale' },
    { value: '6010Z', text: '6010Z - Édition et diffusion de programmes radio' },
    { value: '6020A', text: '6020A - Edition de chaînes généralistes' },
    { value: '6020B', text: '6020B - Edition de chaînes thématiques' },
    { value: '6110Z', text: '6110Z - Télécommunications filaires' },
    { value: '6120Z', text: '6120Z - Télécommunications sans fil' },
    { value: '6130Z', text: '6130Z - Télécommunications par satellite' },
    { value: '6190Z', text: '6190Z - Autres activités de télécommunication' },
    { value: '6201Z', text: '6201Z - Programmation informatique' },
    { value: '6202A', text: '6202A - Conseil en systèmes et logiciels informatiques' },
    { value: '6202B', text: '6202B - Tierce maintenance de systèmes et d\'applications informatiques' },
    { value: '6203Z', text: '6203Z - Gestion d\'installations informatiques' },
    { value: '6209Z', text: '6209Z - Autres activités informatiques' },
    { value: '6311Z', text: '6311Z - Traitement de données, hébergement et activités connexes' },
    { value: '6312Z', text: '6312Z - Portails Internet' },
    { value: '6391Z', text: '6391Z - Activités des agences de presse' },
    { value: '6399Z', text: '6399Z - Autres services d\'information nca' },
    { value: '6411Z', text: '6411Z - Activités de banque centrale' },
    { value: '6419Z', text: '6419Z - Autres intermédiations monétaires' },
    { value: '6420Z', text: '6420Z - Activités des sociétés holding' },
    { value: '6430Z', text: '6430Z - Fonds de placement et entités financières similaires' },
    { value: '6491Z', text: '6491Z - Crédit-bail' },
    { value: '6492Z', text: '6492Z - Autre distribution de crédit' },
    { value: '6499Z', text: '6499Z - Autres activités des services financiers, hors assurance et caisses de retraite, nca' },
    { value: '6511Z', text: '6511Z - Assurance vie' },
    { value: '6512Z', text: '6512Z - Autres assurances' },
    { value: '6520Z', text: '6520Z - Réassurance' },
    { value: '6530Z', text: '6530Z - Caisses de retraite' },
    { value: '6611Z', text: '6611Z - Administration de marchés financiers' },
    { value: '6612Z', text: '6612Z - Courtage de valeurs mobilières et de marchandises' },
    { value: '6619A', text: '6619A - Supports juridiques de gestion de patrimoine mobilier' },
    { value: '6619B', text: '6619B - Autres activités auxiliaires de services financiers, hors assurance et caisses de retraite, nca' },
    { value: '6621Z', text: '6621Z - Évaluation des risques et dommages' },
    { value: '6622Z', text: '6622Z - Activités des agents et courtiers d\'assurances' },
    { value: '6629Z', text: '6629Z - Autres activités auxiliaires d\'assurance et de caisses de retraite' },
    { value: '6630Z', text: '6630Z - Gestion de fonds' },
    { value: '6810Z', text: '6810Z - Activités des marchands de biens immobiliers' },
    { value: '6820A', text: '6820A - Location de logements' },
    { value: '6820B', text: '6820B - Location de terrains et d\'autres biens immobiliers' },
    { value: '6831Z', text: '6831Z - Agences immobilières' },
    { value: '6832A', text: '6832A - Administration d\'immeubles et autres biens immobiliers' },
    { value: '6832B', text: '6832B - Supports juridiques de gestion de patrimoine immobilier' },
    { value: '6910Z', text: '6910Z - Activités juridiques' },
    { value: '6920Z', text: '6920Z - Activités comptables' },
    { value: '7010Z', text: '7010Z - Activités des sièges sociaux' },
    { value: '7021Z', text: '7021Z - Conseil en relations publiques et communication' },
    { value: '7022Z', text: '7022Z - Conseil pour les affaires et autres conseils de gestion' },
    { value: '7111Z', text: '7111Z - Activités d\'architecture' },
    { value: '7112A', text: '7112A - Activité des géomètres' },
    { value: '7112B', text: '7112B - Ingénierie, études techniques' },
    { value: '7120A', text: '7120A - Contrôle technique automobile' },
    { value: '7120B', text: '7120B - Analyses, essais et inspections techniques' },
    { value: '7211Z', text: '7211Z - Recherche-développement en biotechnologie' },
    { value: '7219Z', text: '7219Z - Recherche-développement en autres sciences physiques et naturelles' },
    { value: '7220Z', text: '7220Z - Recherche-développement en sciences humaines et sociales' },
    { value: '7311Z', text: '7311Z - Activités des agences de publicité' },
    { value: '7312Z', text: '7312Z - Régie publicitaire de médias' },
    { value: '7320Z', text: '7320Z - Études de marché et sondages' },
    { value: '7410Z', text: '7410Z - Activités spécialisées de design' },
    { value: '7420Z', text: '7420Z - Activités photographiques' },
    { value: '7430Z', text: '7430Z - Traduction et interprétation' },
    { value: '7490A', text: '7490A - Activité des économistes de la construction' },
    { value: '7490B', text: '7490B - Activités spécialisées, scientifiques et techniques diverses' },
    { value: '7500Z', text: '7500Z - Activités vétérinaires' },
    { value: '7711A', text: '7711A - Location de courte durée de voitures et de véhicules automobiles légers' },
    { value: '7711B', text: '7711B - Location de longue durée de voitures et de véhicules automobiles légers' },
    { value: '7712Z', text: '7712Z - Location et location-bail de camions' },
    { value: '7721Z', text: '7721Z - Location et location-bail d\'articles de loisirs et de sport' },
    { value: '7722Z', text: '7722Z - Location de vidéocassettes et disques vidéo' },
    { value: '7729Z', text: '7729Z - Location et location-bail d\'autres biens personnels et domestiques' },
    { value: '7731Z', text: '7731Z - Location et location-bail de machines et équipements agricoles' },
    { value: '7732Z', text: '7732Z - Location et location-bail de machines et équipements pour la construction' },
    { value: '7733Z', text: '7733Z - Location et location-bail de machines de bureau et de matériel informatique' },
    { value: '7734Z', text: '7734Z - Location et location-bail de matériels de transport par eau' },
    { value: '7735Z', text: '7735Z - Location et location-bail de matériels de transport aérien' },
    { value: '7739Z', text: '7739Z - Location et location-bail d\'autres machines, équipements et biens matériels nca' },
    { value: '7740Z', text: '7740Z - Location-bail de propriété intellectuelle et de produits similaires, à l\'exception des œuvres soumises à copyright' },
    { value: '7810Z', text: '7810Z - Activités des agences de placement de main-d\'œuvre' },
    { value: '7820Z', text: '7820Z - Activités des agences de travail temporaire' },
    { value: '7830Z', text: '7830Z - Autre mise à disposition de ressources humaines' },
    { value: '7911Z', text: '7911Z - Activités des agences de voyage' },
    { value: '7912Z', text: '7912Z - Activités des voyagistes' },
    { value: '7990Z', text: '7990Z - Autres services de réservation et activités connexes' },
    { value: '8010Z', text: '8010Z - Activités de sécurité privée' },
    { value: '8020Z', text: '8020Z - Activités liées aux systèmes de sécurité' },
    { value: '8030Z', text: '8030Z - Activités d\'enquête' },
    { value: '8110Z', text: '8110Z - Activités combinées de soutien lié aux bâtiments' },
    { value: '8121Z', text: '8121Z - Nettoyage courant des bâtiments' },
    { value: '8122Z', text: '8122Z - Autres activités de nettoyage des bâtiments et nettoyage industriel' },
    { value: '8129A', text: '8129A - Désinfection, désinsectisation, dératisation' },
    { value: '8129B', text: '8129B - Autres activités de nettoyage nca' },
    { value: '8130Z', text: '8130Z - Services d\'aménagement paysager' },
    { value: '8211Z', text: '8211Z - Services administratifs combinés de bureau' },
    { value: '8219Z', text: '8219Z - Photocopie, préparation de documents et autres activités spécialisées de soutien de bureau' },
    { value: '8220Z', text: '8220Z - Activités de centres d\'appels' },
    { value: '8230Z', text: '8230Z - Organisation de foires, salons professionnels et congrès' },
    { value: '8291Z', text: '8291Z - Activités des agences de recouvrement de factures et des sociétés d\'information financière sur la clientèle' },
    { value: '8292Z', text: '8292Z - Activités de conditionnement' },
    { value: '8299Z', text: '8299Z - Autres activités de soutien aux entreprises nca' },
    { value: '8411Z', text: '8411Z - Administration publique générale' },
    { value: '8412Z', text: '8412Z - Administration publique (tutelle) de la santé, de la formation, de la culture et des services sociaux, autre que sécurité sociale' },
    { value: '8413Z', text: '8413Z - Administration publique (tutelle) des activités économiques' },
    { value: '8421Z', text: '8421Z - Affaires étrangères' },
    { value: '8422Z', text: '8422Z - Défense' },
    { value: '8423Z', text: '8423Z - Justice' },
    { value: '8424Z', text: '8424Z - Activités d\'ordre public et de sécurité' },
    { value: '8425Z', text: '8425Z - Services du feu et de secours' },
    { value: '8430A', text: '8430A - Activités générales de sécurité sociale' },
    { value: '8430B', text: '8430B - Gestion des retraites complémentaires' },
    { value: '8430C', text: '8430C - Distribution sociale de revenus' },
    { value: '8510Z', text: '8510Z - Enseignement pré-primaire' },
    { value: '8520Z', text: '8520Z - Enseignement primaire' },
    { value: '8531Z', text: '8531Z - Enseignement secondaire général' },
    { value: '8532Z', text: '8532Z - Enseignement secondaire technique ou professionnel' },
    { value: '8541Z', text: '8541Z - Enseignement post-secondaire non supérieur' },
    { value: '8542Z', text: '8542Z - Enseignement supérieur' },
    { value: '8551Z', text: '8551Z - Enseignement de disciplines sportives et d\'activités de loisirs' },
    { value: '8552Z', text: '8552Z - Enseignement culturel' },
    { value: '8553Z', text: '8553Z - Enseignement de la conduite' },
    { value: '8559A', text: '8559A - Formation continue d\'adultes' },
    { value: '8559B', text: '8559B - Autres enseignements' },
    { value: '8560Z', text: '8560Z - Activités de soutien à l\'enseignement' },
    { value: '8610Z', text: '8610Z - Activités hospitalières' },
    { value: '8621Z', text: '8621Z - Activité des médecins généralistes' },
    { value: '8622A', text: '8622A - Activités de radiodiagnostic et de radiothérapie' },
    { value: '8622B', text: '8622B - Activités chirurgicales' },
    { value: '8622C', text: '8622C - Autres activités des médecins spécialistes' },
    { value: '8623Z', text: '8623Z - Pratique dentaire' },
    { value: '8690A', text: '8690A - Ambulances' },
    { value: '8690B', text: '8690B - Laboratoires d\'analyses médicales' },
    { value: '8690C', text: '8690C - Centres de collecte et banques d\'organes' },
    { value: '8690D', text: '8690D - Activités des infirmiers et des sages-femmes' },
    { value: '8690E', text: '8690E - Activités des professionnels de la rééducation, de l\'appareillage et des pédicures-podologues' },
    { value: '8690F', text: '8690F - Activités de santé humaine non classées ailleurs' },
    { value: '8710A', text: '8710A - Hébergement médicalisé pour personnes âgées' },
    { value: '8710B', text: '8710B - Hébergement médicalisés pour enfants handicapés' },
    { value: '8710C', text: '8710C - Hébergement médicalisé pour adultes handicapés et autre hébergement médicalisé' },
    { value: '8720A', text: '8720A - Hébergement social pour handicapés mentaux et malades mentaux' },
    { value: '8720B', text: '8720B - Hébergement social pour toxicomanes' },
    { value: '8730A', text: '8730A - Hébergement social pour personnes âgées' },
    { value: '8730B', text: '8730B - Hébergement social pour handicapés physiques' },
    { value: '8790A', text: '8790A - Hébergement social pour enfants en difficultés' },
    { value: '8790B', text: '8790B - Hébergement social pour adultes et familles en difficultés et autre hébergement social' },
    { value: '8810A', text: '8810A - Aide à domicile' },
    { value: '8810B', text: '8810B - Accueil ou accompagnement sans hébergement d\'adultes handicapés ou de personnes âgées' },
    { value: '8810C', text: '8810C - Aide par le travail' },
    { value: '8891A', text: '8891A - Accueil de jeunes enfants' },
    { value: '8891B', text: '8891B - Accueil ou accompagnement sans hébergement d\'enfants handicapés' },
    { value: '8899A', text: '8899A - Autre accueil ou accompagnement sans hébergement d\'enfants et d\'adolescents' },
    { value: '8899B', text: '8899B - Action sociale sans hébergement nca' },
    { value: '9001Z', text: '9001Z - Arts du spectacle vivant' },
    { value: '9002Z', text: '9002Z - Activités de soutien au spectacle vivant' },
    { value: '9003A', text: '9003A - Création artistique relevant des arts plastiques' },
    { value: '9003B', text: '9003B - Autre création artistique' },
    { value: '9004Z', text: '9004Z - Gestion de salles de spectacles' },
    { value: '9101Z', text: '9101Z - Gestion des bibliothèques et des archives' },
    { value: '9102Z', text: '9102Z - Gestion des musées' },
    { value: '9103Z', text: '9103Z - Gestion des sites et monuments historiques et des attractions touristiques similaires' },
    { value: '9104Z', text: '9104Z - Gestion des jardins botaniques et zoologiques et des réserves naturelles' },
    { value: '9200Z', text: '9200Z - Organisation de jeux de hasard et d\'argent' },
    { value: '9311Z', text: '9311Z - Gestion d\'installations sportives' },
    { value: '9312Z', text: '9312Z - Activités de clubs de sports' },
    { value: '9313Z', text: '9313Z - Activités des centres de culture physique' },
    { value: '9319Z', text: '9319Z - Autres activités liées au sport' },
    { value: '9321Z', text: '9321Z - Activités des parcs d\'attractions et parcs à thèmes' },
    { value: '9329Z', text: '9329Z - Autres activités récréatives et de loisirs' },
    { value: '9411Z', text: '9411Z - Activités des organisations patronales et consulaires' },
    { value: '9412Z', text: '9412Z - Activités des organisations professionnelles' },
    { value: '9420Z', text: '9420Z - Activités des syndicats de salariés' },
    { value: '9491Z', text: '9491Z - Activités des organisations religieuses' },
    { value: '9492Z', text: '9492Z - Activités des organisations politiques' },
    { value: '9499Z', text: '9499Z - Autres organisations fonctionnant par adhésion volontaire' },
    { value: '9511Z', text: '9511Z - Réparation d\'ordinateurs et d\'équipements périphériques' },
    { value: '9512Z', text: '9512Z - Réparation d\'équipements de communication' },
    { value: '9521Z', text: '9521Z - Réparation de produits électroniques grand public' },
    { value: '9522Z', text: '9522Z - Réparation d\'appareils électroménagers et d\'équipements pour la maison et le jardin' },
    { value: '9523Z', text: '9523Z - Réparation de chaussures et d\'articles en cuir' },
    { value: '9524Z', text: '9524Z - Réparation de meubles et d\'équipements du foyer' },
    { value: '9525Z', text: '9525Z - Réparation d\'articles d\'horlogerie et de bijouterie' },
    { value: '9529Z', text: '9529Z - Réparation d\'autres biens personnels et domestiques' },
    { value: '9601A', text: '9601A - Blanchisserie-teinturerie de gros' },
    { value: '9601B', text: '9601B - Blanchisserie-teinturerie de détail' },
    { value: '9602A', text: '9602A - Coiffure' },
    { value: '9602B', text: '9602B - Soins de beauté' },
    { value: '9603Z', text: '9603Z - Services funéraires' },
    { value: '9604Z', text: '9604Z - Entretien corporel' },
    { value: '9609Z', text: '9609Z - Autres services personnels nca' },
    { value: '9700Z', text: '9700Z - Activités des ménages en tant qu\'employeurs de personnel domestique' },
    { value: '9810Z', text: '9810Z - Activités indifférenciées des ménages en tant que producteurs de biens pour usage propre' },
    { value: '9820Z', text: '9820Z - Activités indifférenciées des ménages en tant que producteurs de services pour usage propre' },
    { value: '9900Z', text: '9900Z - Activités des organisations et organismes extraterritoriaux' }
];
