export const companyFormList = [
    'Affaire Personnelle agent commercial',
    'Affaire personnelle artisan',
    'Affaire personnelle artisan commerçant',
    'Affaire personnelle commerçant',
    'Affaire personnelle exploitant agricole',
    'Affaire personnelle gérant associé de société',
    'Affaire personnelle personne physique',
    'Affaire personnelle profession libérale',
    'Association de droit local (Bas-Rhin Haut-Rhin et Moselle)',
    'Association déclarée',
    'Association déclarée reconnue d\'utilité publique',
    'Association intermédiaire',
    'Auto entrepreneur',
    'Comité central d\'entreprise',
    'Comité d\'établissement',
    'Commune et commune nouvelle',
    'EARL - Exploitation agricole à responsabilité limitée',
    'Etablissement public association syndicale autorisée',
    'Etablissement public local d\'enseignement',
    'Etablissement public syndical à vocation multiple',
    'Etablissement public syndicat mixte communal',
    'EI - Entreprise individuelle',
    'EIRL - Entrepreneur individuel à responsabilité limitée',
    'EURL - Entreprise unipersonnelle à responsabilité limitée',
    'Groupement agricole d\'exploitation en commun',
    'Groupement de droit privé non doté de la personnalité morale',
    'Groupement d\'intérêt économique',
    'Groupement foncier agricole',
    'Indivision entre personnes physiques',
    'SA - Société Anonyme',
    'SA à conseil d\'administration',
    'SA à directoire',
    'SA coopérative à conseil d\'administration',
    'SA coopérative de consommation à directoire',
    'SARL - Société à responsabilité limitée',
    'SARL coopérative ouvrière de production (SCOP)',
    'SARL unipersonnelle',
    'SASU Société par actions simplifiée à associé unique',
    'Société à responsabilité limitée',
    'Société à responsabilité limitée coopérative artisanale',
    'Société à responsabilité limitée nationale',
    'Société civile',
    'Société civile de moyens',
    'Société civile d\'exploitation agricole SCEA',
    'Société civile immobilière',
    'Société civile immobilière de construction - vente',
    'Société civile professionnelle',
    'Société civile professionnelle d\'architectes',
    'Société coopérative agricole',
    'Société coopérative exploitée sous forme de SARL',
    'Société d exercice libéral par action simplifiée',
    'Société de droit étranger',
    'Société de fait entre personnes physiques',
    'Société d\'exercice libéral à responsabilité limitée',
    'Société d\'intérêt collectif agricole',
    'Société d\'intérêt collectif agricole exploitée sous forme de SARL',
    'Société en commandite simple',
    'Société en nom collectif',
    'Société étrangère immatriculée au RCS',
    'Société étrangère non immatriculée au RCS',
    'Société européenne',
    'Société par actions simplifiée',
    'Syndicat de copropriété',
].map(value => { return { text: value, value: value } });
