export const industries = [
    'Animaux - Centre équestre',
    'Animaux – Élevage',
    'Animaux - Garde',
    'Animaux - Médecine (vétérinaire, ostéopathe, etc.)',
    'Animaux - Médecine parallèle',
    'Animaux - Toilettage',
    'Animaux - Autre',
    'Auto - Carrossier',
    'Auto - Contrôle technique',
    'Auto - Dépannage',
    'Auto - Garage automobile',
    'Auto - Garage moto',
    'Auto - Location et vente de vélo',
    'Auto - Nettoyage / entretien',
    'Auto - Vente de pièces et accessoires',
    'Auto - Vente et location de véhicules d\'occasions',
    'Auto - Vente et réparation de machines agricoles',
    'Auto - Autre',
    'Bâtiment - Aménagement extérieur',
    'Bâtiment - Agencement d\'intérieur / décoration',
    'Bâtiment - Architecte',
    'Bâtiment - Artisan multiservices',
    'Bâtiment - Assainissement',
    'Bâtiment - Carreleur',
    'Bâtiment - Charpentier / Couvreur',
    'Bâtiment - Climatisation / chauffage',
    'Bâtiment - Constructeur de maison',
    'Bâtiment - Décapage / Désensablage',
    'Bâtiment - Démolition',
    'Bâtiment - Électricien',
    'Bâtiment - Entretien / nettoyage',
    'Bâtiment - Façadier',
    'Bâtiment - Ferronnerie',
    'Bâtiment - Géomètre / maitre d\'oeuvre',
    'Bâtiment - Isolation / étanchéité',
    'Bâtiment - Maçon',
    'Bâtiment - Métallerie',
    'Bâtiment - Menuisier',
    'Bâtiment - Paysagiste',
    'Bâtiment - Piscine',
    'Bâtiment - Plâtrier / peintre',
    'Bâtiment - Plombier',
    'Bâtiment - Ramonage',
    'Bâtiment - Rénovation',
    'Bâtiment - Serrurerie',
    'Bâtiment - Travaux publics',
    'Bâtiment - Technicien bureau d\'étude',
    'Bâtiment - Terrassement',
    'Bâtiment - Vente matériaux',
    'Bâtiment - Autre',
    'Beauté - Coiffure',
    'Beauté - Cosmétique',
    'Beauté - Esthétique',
    'Beauté - Tatouage',
    'Beauté - Autre',
    'Bien-être - Autre',
    'Bien-être - Développement personnel',
    'Bien-être - Massage',
    'Bien-être - Naturopathe',
    'Bien-être - Soin énergétique',
    'Bien-être - Sophrologue',
    'Commerce - Atelier de créateur',
    'Commerce - Bijouterie',
    'Commerce - Boucherie / charcuterie',
    'Commerce - Boulangerie / pâtisserie',
    'Commerce - Caviste',
    'Commerce - Cuisine / salle de bain',
    'Commerce - Décoration d\'intérieur',
    'Commerce - Destockage',
    'Commerce - Épicerie',
    'Commerce - Fleuriste',
    'Commerce - Fromagerie',
    'Commerce - Grossiste',
    'Commerce - Informatique / téléphonie',
    'Commerce - Librairie/Papeterie',
    'Commerce - Location / vente d\'équipement sportif',
    'Commerce - Mercerie',
    'Commerce - Meuble',
    'Commerce - Musique',
    'Commerce - Opticien',
    'Commerce - Pharmacie',
    'Commerce - Poissonerie',
    'Commerce - Primeur',
    'Commerce - Vente matériaux',
    'Commerce - Vente de cigarette électronique',
    'Commerce - Vente de nourriture et d\'accessoire pour animaux',
    'Commerce - Vêtement',
    'Commerce - Sport',
    'Commerce - Autre',
    'Culture - Apiculture',
    'Culture - Horticulture',
    'Culture - Vigne',
    'Culture - Autre',
    'Formation - Auto-école',
    'Formation - Enseignement / scolaire',
    'Formation - Professionnel',
    'Formation - Autre',
    'Hébergement - Camping',
    "Hébergement - Gîte / chambre d'hôte",
    'Hébergement - Hôtel',
    'Hébergement - Location logement',
    'Hébergement - Maison de retraite',
    'Hébergement - Autre',
    'Restauration - Café / brasserie',
    'Restauration - Restaurant',
    'Restauration - Restauration rapide',
    'Restauration - Traiteur',
    'Restauration - Autre',
    'Santé - Dentiste',
    'Santé - Diététicien',
    'Santé - Infirmier',
    'Santé - Kinésithérapeute',
    'Santé - Matériel de santé',
    'Santé - Médecin',
    'Santé - Ostéopathe',
    'Santé - Psychologue',
    'Santé - Autre',
    'Service - Aide à domicile',
    'Service - Ambulance',
    'Service - Association',
    'Service - Assurance',
    'Service - Avocat',
    'Service - Boîte de nuit/DJ',
    'Service - Comptable',
    'Service - Conciergerie',
    'Service - Conseil',
    'Service - Couturière',
    'Service - Crèche / garde d\'enfant',
    'Service - Désinfection',
    'Service - Entretien / nettoyage',
    'Service - Évènementiel',
    'Service - Immobilier',
    'Service - Imprimerie / vente d\'objets publicitaires',
    'Service - Informatique',
    'Service - Installateur',
    'Service - Juriste',
    'Service - Loisir',
    'Service - Location matériel/salle',
    'Service - Musicien',
    'Service - Nettoyage',
    'Service - Notaire',
    'Service - Photographe',
    'Service - Pompes funèbres',
    'Service - Pressing',
    'Service - Salle de sport',
    'Service - Secrétariat / assistant administratif',
    'Service - Sécurité',
    'Service - Serrurier',
    'Service - Stockage',
    'Service - Taxi',
    'Service - Transport / déménagement',
    'Service - Voyagiste',
    'Service - VTC',
    'Service - Autre'
].map(value => { return { text: value, value: value } });
